[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Patch in perma debuff for solar flare
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if self.ability and self.ability.perma_debuff then self.debuff = true end'''
position = 'after'
payload = '''
if self.actually_permanent_debuff then self.debuff = true end'''
match_indent = true

# Fix exact hand oneshot not counting as oneshot
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
position = 'at'
pattern = '''
SMODS.last_hand_oneshot = SMODS.calculate_round_score() > G.GAME.blind.chips'''
payload = '''
    SMODS.last_hand_oneshot = SMODS.calculate_round_score() >= G.GAME.blind.chips'''
