[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Support modules in generate_card_ui
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
match_indent = true
position = 'before'
pattern = '''
elseif _c.set == 'Joker' then
'''
payload = '''
elseif _c.set == 'tbp_module' then
    localize{type = 'descriptions', set = 'tbp_module', key = _c.key, nodes = desc_nodes, text_colour = darken(Wormhole.tbp.module_colours[_c.module_type], 0.15), vars = specific_vars or _c.vars, background_colour = G.C.BLUE}
    desc_nodes.tbp_module = _c.module_type
    desc_nodes.module_info = _c.module_info
'''

# small ship thing
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.discard = CardArea("
position = "before"
match_indent = true
payload = '''
self.worm_tbp_sprites = self.worm_tbp_sprites or {}
G.worm_tbp_sprites['small_ship'] = SMODS.create_sprite(0,0,G.CARD_W,G.CARD_H,"worm_tbp_small_ship", {x=0,y=0})
'''

# Add module info_boxes
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
match_indent = true
position = 'after'
pattern = '''
local info_boxes = {}
'''
payload = '''
local tbp_module_info_boxes = {}
'''

# Modify info_queue to add spaceship modules
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
match_indent = true
position = 'at'
pattern = '''
info_boxes[#info_boxes+1] =
          {n=G.UIT.R, config={align = "cm"}, nodes={
          {n=G.UIT.R, config={align = "cm", colour = lighten(G.C.JOKER_GREY, 0.5), r = 0.1, padding = 0.05, emboss = 0.05}, nodes={
            info_tip_from_rows(v, v.name),
                      }}
                    }}
'''
payload = '''
if v.tbp_module then
    tbp_module_info_boxes[#tbp_module_info_boxes+1] = {n=G.UIT.R, config={align = "cl"}, nodes={
        {n=G.UIT.R, config={align = "cm", colour = darken(Wormhole.tbp.module_colours[v.tbp_module], 0.5), padding = 0.05, emboss = 0.1}, nodes={
            Wormhole.tbp.module_tooltip(v),
        }}
    }}
else
    info_boxes[#info_boxes+1] =
        {n=G.UIT.R, config={align = "cm"}, nodes={
            {n=G.UIT.R, config={align = "cm", colour = lighten(G.C.JOKER_GREY, 0.5), r = 0.1, padding = 0.05, emboss = 0.05}, nodes={
                info_tip_from_rows(v, v.name),
            }}
        }}
end
'''
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
match_indent = true
position = 'before'
pattern = '''
if multi_boxes[1] then
'''
payload = '''
if next(tbp_module_info_boxes) then
    ret_val.nodes[#ret_val.nodes + 1] = {n=G.UIT.C, config={align = "cm", func = 'show_spaceship_tooltips',object = Moveable(), collection = card.area.config.collection and card.T.x, ref_table = next(tbp_module_info_boxes) and tbp_module_info_boxes or nil}, nodes={}}
end
'''

# Flag info_queue on spaceship
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
match_indent = true
position = 'after'
pattern = '''
info_boxes = {{n=G.UIT.R, config = {align="cm", padding = 0.05, card_pos = card.T.x }, nodes = info_cols}}
'''
payload = '''
if card.config.center_key == 'j_worm_tbp_spaceship' then info_boxes[1].config.tbp_spaceship = true; info_boxes[1].config.tbp_collection = card.area.config.collection end
'''


[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "love.graphics.draw(last_canvas, 0, 0)"
position = "after"
payload = '''
if shader.key == "worm_tbp_space_warp" then
    love.graphics.setCanvas({current_canvas, stencil = true})
    for k, v in ipairs(Wormhole.tbp.shader_draw_stuff) do
        if v and v.translate_container then
            love.graphics.push("all")
            love.graphics.setShader()
            G.OVERLAY_TUTORIAL = true
            v:translate_container()
            v:draw()
            G.OVERLAY_TUTORIAL = nil
            love.graphics.pop()
        end
    end
    if G.GAME.module_replace_overlay and G.GAME.module_replace_overlay.translate_container then
        love.graphics.push("all")
        love.graphics.setShader()
        G.OVERLAY_TUTORIAL = true
        G.GAME.module_replace_overlay:translate_container()
        G.GAME.module_replace_overlay:draw()
        G.OVERLAY_TUTORIAL = nil
        love.graphics.pop()
    end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
self.shared_seals = {
    Gold = Sprite(0, 0, self.CARD_W, self.CARD_H, self.ASSET_ATLAS["centers"], {x = 2,y = 0}),
    Purple = Sprite(0, 0, self.CARD_W, self.CARD_H, self.ASSET_ATLAS["centers"], {x = 4,y = 4}),
    Red = Sprite(0, 0, self.CARD_W, self.CARD_H, self.ASSET_ATLAS["centers"], {x = 5,y = 4}),
    Blue = Sprite(0, 0, self.CARD_W, self.CARD_H, self.ASSET_ATLAS["centers"], {x = 6,y = 4}),
}
'''
position = "after"
payload = '''
self.tbp = {}
self.tbp.module_sprites = {}
'''
match_indent = true

# Temporary patch until SMODS release for info_queue names, expected to fail later
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = '''
if (full_UI_table.from_detailed_tooltip and full_UI_table.info[1] == desc_nodes) 
'''
position = "at"
payload = '''
if (not full_UI_table.from_detailed_tooltip or full_UI_table.info[1] == desc_nodes)
'''
match_indent = true

# Fix shadow
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/card_draw.lua"]'
pattern = '''
G.shared_shadow = self.sprite_facing == 'front' and self.children.center or self.children.back
'''
position = "after"
payload = '''
G.shared_shadow = (self.config.center.set == 'tbp_module' or self.config.center.atlas == 'worm_tbp_ship') and self.children.back or G.shared_shadow 
'''
match_indent = true