[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# adds the satellite tab
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{
            label = localize('b_poker_hands'),
            chosen = true,
            tab_definition_function = create_UIBox_current_hands,
        },'''
match_indent = true
position = "after"
payload = '''
          {
            label = localize('b_worm_jr_satellites'),
            colour = G.C.SECONDARY_SET.worm_jr_satellite,
            tab_definition_function = Wormhole.JR_UTILS.create_UIBox_current_satellites,
        },
'''

# allows individual tab buttons to be different colours
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
tab_buttons[#tab_buttons+1] = UIBox_button({id = 'tab_but_'..(v.label or ''), ref_table = v, button = 'change_tab', label = {v.label}, minh = 0.8*args.scale, minw = 2.5*args.scale, col = true, choice = true, scale = args.text_scale, chosen = v.chosen, func = v.func, colour = args.colour, focus_args = {type = 'none'}})
'''
match_indent = true
position = "at"
payload = '''
tab_buttons[#tab_buttons+1] = UIBox_button({id = 'tab_but_'..(v.label or ''), ref_table = v, button = 'change_tab', label = {v.label}, minh = 0.8*args.scale, minw = 2.5*args.scale, col = true, choice = true, scale = args.text_scale, chosen = v.chosen, func = v.func, colour = v.colour or args.colour, focus_args = {type = 'none'}})
'''
