[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

# lemniscate tomorrow
# PotatoPatchUtils.CREDITS.create_team_credit_page
[[patches]]
[patches.pattern]
target = '=[SMODS PotatoPatchUtils "src/credits.lua"]'
pattern = 'self:juice_up(0.05, 0.03)'
position = 'before'
payload = '''
if member.name == "InvalidOS" and member.team == "Lancer Fan Club" then
    info_nodes.nodes[1].nodes[3].nodes[1].nodes[1].nodes[1] = { n=G.UIT.R, config = { align="cm" }, nodes = {
        { n=G.UIT.O, config = { object = Wormhole.LancerFanClub.Alexi.create_lemniscate() }}
    }}
end
'''
match_indent = true
