[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
update_hand_text({sound = G.GAME.current_round.current_hand.handname ~= disp_text and 'button' or nil, volume = 0.4, immediate = true, nopulse = nil,
delay = G.GAME.current_round.current_hand.handname ~= disp_text and 0.4 or 0}, {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult, chips = G.GAME.hands[text].chips})
'''
position = "at"
payload = '''
local junks = 0
for i, v in pairs(scoring_hand) do
    if v.config.center.key == "m_worm_ct_junk_card" then junks = junks + 1 end
end
G.GAME.worm_c3_junk_stats.x_hand_stats = G.GAME.worm_c3_junk_stats.x_hand_stats or 1.5
local junk_hands_mult = G.GAME.worm_c3_junk_stats.x_hand_stats ^ junks

update_hand_text({sound = G.GAME.current_round.current_hand.handname ~= disp_text and 'button' or nil, volume = 0.4, immediate = true, nopulse = nil,
    delay = G.GAME.current_round.current_hand.handname ~= disp_text and 0.4 or 0}, 
    {handname=disp_text, level=G.GAME.hands[text].level, mult = G.GAME.hands[text].mult * junk_hands_mult, chips = G.GAME.hands[text].chips * junk_hands_mult})
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
mult = mod_mult(G.GAME.hands[text].mult)
hand_chips = mod_chips(G.GAME.hands[text].chips)
'''
position = "at"
payload = '''
mult = mod_mult(G.GAME.hands[text].mult * junk_hands_mult)
hand_chips = mod_chips(G.GAME.hands[text].chips * junk_hands_mult)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
    if G.SPLASH_BACK then
        if G.debug_background_toggle then
            love.graphics.clear({0,1,0,1})
        else
            love.graphics.push()
            G.SPLASH_BACK:translate_container()
            G.SPLASH_BACK:draw()
            love.graphics.pop()
        end
    end
'''
position = 'after'
payload = '''
    if G.SPLASH_JUNK_PACK then
        if G.debug_background_toggle then
            
        else
            love.graphics.push()
            G.SPLASH_JUNK_PACK:translate_container()
            G.SPLASH_JUNK_PACK:draw()
            love.graphics.pop()
        end
    end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''
local t = {
    n = G.UIT.O,
'''
position = 'before'
payload = '''
if not in_collection then
    local has_junk = false
    for k, v in pairs(G.playing_cards) do
        if SMODS.has_enhancement(v, "m_worm_ct_junk_card") then
            has_junk = true
            break
        end
    end
    if has_junk or (G.GAME and G.GAME.worm_c3_junk_stats and G.GAME.worm_c3_junk_stats.x_hand_stats ~= 1.5) then
        table.insert(object.nodes[1].nodes, create_UIBox_junk_hand_row())
    end
end
'''
match_indent = true
