# TheOneGoofAli's loading screen patches.

[manifest]
version = "1.0.0"
dump_lua = true
priority = 5

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = ["content/Dummies/loadlogo.lua"]
