[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]] 
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
{n=G.UIT.R, config={align = "cm", padding = 0.05, r = 0.1, colour = darken(G.C.JOKER_GREY, 0.1), emboss = 0.05, hover = true, force_focus = true, on_demand_tooltip = {text = localize(handname, 'poker_hand_descriptions'), filler = {func = create_UIBox_hand_tip, args = handname}}}, nodes={
'''
position = "at"
payload = '''
{n=G.UIT.R, config={align = "cm", padding = 0.05, r = 0.1, colour = thorn_renamelater_deck_played_this_ante(handname) and darken(G.C.PURPLE, 0.2) or darken(G.C.JOKER_GREY, 0.1), emboss = 0.05, hover = true, force_focus = true, on_demand_tooltip = {text = localize(handname, 'poker_hand_descriptions'), filler = {func = create_UIBox_hand_tip, args = handname}}}, nodes={
'''
match_indent = true